### PR TITLE
Added dotenv to resolve error Environment variable not found: DATABAS…

### PR DESCRIPTION
**Pull request by Fi1osof**
Environment variable not found: DATABASE_URL

### CODE REVIEW

**Comment by AhmedElywa** [comment]
this repo just an example you can build one like it with `pal c` command or copy this repo to your profile and update it.
we use this repo to make a live preview on Vercel and we already added the Environment variable to Vercel settings

**Comment by AhmedElywa** [comment]
Also, you can just add the `.env` file into prisma folder and prisma will read it without using `dotenv` package

**Comment by Fi1osof** [comment]
It's works on vercel, but not local. With this works with local too.

**Comment by AhmedElywa** [comment]
It's working on my local too

**Comment by Fi1osof** [comment]
> Also, you can just add the `.env` file into prisma folder and prisma will read it without using `dotenv` package

Yea, i do this before, but got error. Maybe i do some wrong. Sorry to bother.

**Comment by AhmedElywa** [comment]
If you need any help, you can ask on prisma slack. they are very friendly

**Pull request closed without merging**
